apiVersion: v1
kind: Namespace
metadata:
  name: foo
  labels:
    environment-id: env_579884d0-4c18-49fb-b7a1-7ddec14877d0
    project-id: project_0cdefd3c-20e4-490e-8c33-6ac7087e82c7
    project-name: xammy
    environment-name: dev
    organization-id: org_01b50229-db34-43d4-8f3e-d1aeb683d900
